---
title: An R Markdown document converted from "R_0607fig4.ipynb"
output: html_document
---

## Pairwise comparison

```{r}
library(stringr)
library(ggplot2)
install.packages("ggpubr")
library(ggpubr)
```

```{r}
vdir=""
###IP
cfm="^I\\d+|^P\\d+|^AC\\d+"

csp=read.csv(file=paste0(vdir,"cnt-sp-norm-",'1105',".csv"),header=T,sep=',',as.is=F)
nsp=csp[intersect(grep(cfm,csp$a), grep(cfm,csp$b)),]
nsp=cbind(nsp,ab=paste(nsp[,'a'],nsp[,'b'],sep=","),
          ahost=NA,bhost=NA,shost=F,length=0)
spl=read.csv(file=paste0(vdir,"viruslist-single-pan","1105",".tsv"),header=T,sep='\t',as.is=F)
nspl=spl[grep(cfm,spl$Abre),c('Abre','Length','EukTree','Family','aanum','gf.unique.fm','gf.shared')]
nsp=nsp[intersect(which(nsp[,'a'] %in% nspl[,'Abre']),which(nsp[,'b'] %in% nspl[,'Abre'])),]
# as.numeric(sub("I","",nspl$Abre[tail(grep('^I\\d+',nspl$Abre),1)]))
change=cbind(old=c(paste0("AC0",1:length(grep("^AC\\d+",nspl$Abre)))),
  new=c(paste0("I",(length(grep('^I\\d+',nspl$Abre))+1):((length(grep('^I\\d+',nspl$Abre))+1)+length(grep("^AC\\d+",nspl$Abre))-1))))

for(i in 1:nrow(change)){
  levels(nspl[,'Abre'])[which(levels(nspl[,'Abre'])==change[i,'old'])]=change[i,'new']
  levels(nsp[,'a'])[which(levels(nsp[,'a'])==change[i,'old'])]=change[i,'new']
  levels(nsp[,'b'])[which(levels(nsp[,'b'])==change[i,'old'])]=change[i,'new']
}

nsp=nsp[-which(str_extract(nsp[,'a'],"\\D+")==str_extract(nsp[,'b'],"\\D+")),]




for(i in 1:nrow(nsp)){
  nsp[i,'ahost']=as.character(nspl[grep(nsp[i,'a'],nspl[,'Abre']),'EukTree'])
  nsp[i,'bhost']=as.character(nspl[grep(nsp[i,'b'],nspl[,'Abre']),'EukTree'])
  nsp[i,'length']=sqrt(as.numeric(nspl[grep(nsp[i,'a'],nspl[,'Abre']),'Length'])*
    as.numeric(nspl[grep(nsp[i,'b'],nspl[,'Abre']),'Length']))
  nsp[i,'aamean']=sqrt(as.numeric(nspl[grep(nsp[i,'a'],nspl[,'Abre']),'aanum'])*
    as.numeric(nspl[grep(nsp[i,'b'],nspl[,'Abre']),'aanum']))
  nsp[i,'gpmean']=sqrt((as.numeric(nspl[grep(nsp[i,'a'],nspl[,'Abre']),'gf.unique.fm'])+
    as.numeric(nspl[grep(nsp[i,'a'],nspl[,'Abre']),'gf.shared']))*
      (as.numeric(nspl[grep(nsp[i,'b'],nspl[,'Abre']),'gf.unique.fm'])+
        as.numeric(nspl[grep(nsp[i,'b'],nspl[,'Abre']),'gf.shared'])))
  nsp[i,grep("ptera",nsp[i,])]="Insect"
  nsp[i,grep("Fish|ia$|Aves",nsp[i,])]="Vertebrate"
  if(nsp[i,'ahost']==nsp[i,'bhost']){nsp[i,'shost']=T}
  else{nsp[i,'shost']=F}
}

simhost=nsp[-which(nsp[,'shost']==F),]
sss=nsp[which(nsp[,'shost']==T),]
sss=unique(sss[,'ahost']) # shared hosts

#setdiff(which(nsp[,'shost']==F),intersect(which(nsp[,'ahost'] %in% sss),which(nsp[,'bhost'] %in% sss)))
difhost=nsp[setdiff(which(nsp[,'shost']==F),intersect(which(nsp[,'ahost'] %in% sss),which(nsp[,'bhost'] %in% sss))),]
simhost.l=c(as.character(unique(simhost[,'a'])),as.character(unique(simhost[,'b'])))

tdifhost=difhost[intersect(which(difhost[,'a'] %in% simhost.l),which(difhost[,'b'] %in% simhost.l)),]
```

```{r}
pdf(paste0(vdir,'','P-I-0525.pdf'),
    width=8.268/2.1,height=11.693/4.2,paper='special')
pval=NULL; pvind=1
for(ht in sss){
  alist=nsp[union(which(nsp[,'ahost']==ht),which(nsp[,'bhost']==ht)),]
  simhost=alist[-which(alist[,'shost']==F),]
  difhost=alist[-which(alist[,'shost']==T),]
  
  gpval='gpnorm'
  pval[pvind]=wilcox.test(difhost[,gpval],simhost[,gpval],mu=0,alternative="less",conf.int=T)$p.value; pvind=pvind+1

  vio=ggplot(alist, aes(x=shost,y=alist[,gpval]))+
    geom_violin()+theme_linedraw()+geom_boxplot(width=0.05)+
    #geom_dotplot(binaxis='y', stackdir='center', dotsize=0.1)+#geom_jitter(width=0.25,size=0.5)+
    theme(axis.text.x=element_text(size=8),
      axis.text.y=element_text(size=10), axis.title=element_text(size=10))+
    scale_x_discrete(labels=c(paste0(ht," & non-",ht),paste0(ht,' & ',ht)))+
    labs(x=paste0(length(which(!alist$shost)),"  ",length(which(alist$shost))), 
      y=paste0("Proportion of genes shared"))+ #
    stat_compare_means(label.x=1.2,label.y=max(nsp[,gpval])) #aes(label=..p.signif..),

  print(vio);#print(s);print(d)

}
dev.off()
```

```{r}

```

```{r}
## file processing
cfm="^MI\\d+|^PY\\d+|^MP\\d+|^PN\\d+|^ME\\d+"

csp=read.csv(file=paste0(vdir,"cnt-sp-norm-",'1105',".csv"),header=T,sep=',',as.is=F)
nsp=csp[intersect(grep(cfm,csp$a), grep(cfm,csp$b)),]
nsp=cbind(nsp,ab=paste(nsp[,'a'],nsp[,'b'],sep=","),
          ahost=NA,bhost=NA,shost=F,length=0)

spl=read.csv(file=paste0(vdir,"viruslist-single-pan","1105",".tsv"),header=T,sep='\t',as.is=F)
nspl=spl[grep(cfm,spl$Abre),c('Abre','Length','EukTree','Family','aanum','gf.unique.fm','gf.shared')]

nspl=nspl[-which(nspl[,'EukTree']==""),]
nsp=nsp[intersect(which(nsp[,'a'] %in% nspl[,'Abre']),which(nsp[,'b'] %in% nspl[,'Abre'])),]

change=cbind(old=c(as.character(nspl$Abre[grep("^MP\\d+",nspl$Abre)]),paste0("PN0",1:length(grep("^PN\\d+",nspl$Abre)))),
  new=c(paste0("MI",(max(as.numeric(sub("\\D+","",nspl$Abre[grep('^MI\\d+',nspl$Abre)])))+1):
    ((max(as.numeric(sub("\\D+","",nspl$Abre[grep('^MI\\d+',nspl$Abre)])))+1)+length(grep("^MP\\d+",nspl$Abre))-1)),
  paste0("PY",(max(as.numeric(sub("\\D+","",nspl$Abre[grep('^PY\\d+',nspl$Abre)])))+1):
    ((max(as.numeric(sub("\\D+","",nspl$Abre[grep('^PY\\d+',nspl$Abre)])))+1)+length(grep("^PN\\d+",nspl$Abre))-1))))



for(i in 1:nrow(change)){
  levels(nspl[,'Abre'])[which(levels(nspl[,'Abre'])==change[i,'old'])]=change[i,'new']
  levels(nsp[,'a'])[which(levels(nsp[,'a'])==change[i,'old'])]=change[i,'new']
  levels(nsp[,'b'])[which(levels(nsp[,'b'])==change[i,'old'])]=change[i,'new']
}

nsp=nsp[-which(str_extract(nsp[,'a'],"\\D+")==str_extract(nsp[,'b'],"\\D+")),]


for(i in 1:nrow(nsp)){
  nsp[i,'ahost']=as.character(nspl[grep(nsp[i,'a'],nspl[,'Abre']),'EukTree'])
  nsp[i,'bhost']=as.character(nspl[grep(nsp[i,'b'],nspl[,'Abre']),'EukTree'])
  nsp[i,'length']=sqrt(as.numeric(nspl[grep(nsp[i,'a'],nspl[,'Abre']),'Length'])*
    as.numeric(nspl[grep(nsp[i,'b'],nspl[,'Abre']),'Length']))
  nsp[i,'aamean']=sqrt(as.numeric(nspl[grep(nsp[i,'a'],nspl[,'Abre']),'aanum'])*
    as.numeric(nspl[grep(nsp[i,'b'],nspl[,'Abre']),'aanum']))
  nsp[i,'gpmean']=sqrt((as.numeric(nspl[grep(nsp[i,'a'],nspl[,'Abre']),'gf.unique.fm'])+
    as.numeric(nspl[grep(nsp[i,'a'],nspl[,'Abre']),'gf.shared']))*
      (as.numeric(nspl[grep(nsp[i,'b'],nspl[,'Abre']),'gf.unique.fm'])+
        as.numeric(nspl[grep(nsp[i,'b'],nspl[,'Abre']),'gf.shared'])))
  #nsp[i,grep("treboux|mamiello",nsp[i,])]="chlorophytes"
  #nsp[i,grep("bicosoec|raphido|pelagophy|macroalg",nsp[i,])]="stramenopiles"
  nsp[i,grep("phyceae|ales|coccus|monas",nsp[i,])]="algae"
  #"Treboux|mamiello|raphido|pelagophy|macroalg|haptophy"
  nsp[i,grep("Bicos|Choano|Eubod",nsp[i,])]="hetero_flg"
  #nsp[i,grep("haptophy",nsp[i,])]="haptophytes"
  nsp[i,grep("Tubuline|Discosea",nsp[i,])]="amoeba"
  if(nsp[i,'ahost']==nsp[i,'bhost']){nsp[i,'shost']=T}else{
    nsp[i,'shost']=F}
}

simhost=nsp[-which(nsp[,'shost']==F),]
sss=nsp[which(nsp[,'shost']==T),]
sss=unique(sss[,'ahost']) # shared hosts

#setdiff(which(nsp[,'shost']==F),intersect(which(nsp[,'ahost'] %in% sss),which(nsp[,'bhost'] %in% sss)))
difhost=nsp[setdiff(which(nsp[,'shost']==F),intersect(which(nsp[,'ahost'] %in% sss),which(nsp[,'bhost'] %in% sss))),]
```

```{r}
pdf(paste0(vdir,'','MI-PY-0525.pdf'),
   width=8.268/2.1,height=11.693/4.2,paper='special')
pval=NULL; pvind=1
for(ht in sss){
  alist=nsp[union(which(nsp[,'ahost']==ht),which(nsp[,'bhost']==ht)),]
  simhost=alist[-which(alist[,'shost']==F),]
  difhost=alist[-which(alist[,'shost']==T),]
  
  gpval='gpnorm'
  pval[pvind]=wilcox.test(difhost[,gpval],simhost[,gpval],mu=0,alternative="less",conf.int=T)$p.value; pvind=pvind+1

  vio=ggplot(alist, aes(x=shost,y=alist[,gpval]))+
    geom_violin()+theme_linedraw()+geom_boxplot(width=0.05)+
    #geom_dotplot(binaxis='y', stackdir='center', dotsize=0.1)+#geom_jitter(width=0.25,size=0.5)+
    theme(axis.text.x=element_text(size=8),
      axis.text.y=element_text(size=10), axis.title=element_text(size=10))+
    scale_x_discrete(labels=c(paste0(ht," & non-",ht),paste0(ht,' & ',ht)))+
    labs(x=paste0(length(which(!alist$shost)),"  ",length(which(alist$shost))), 
      y=paste0("proportion of genes shared"))+ #
    stat_compare_means(label.x=1.2,label.y=max(nsp[,gpval]))

  print(vio);#print(s);print(d)


}
dev.off()
```

